apiVersion: v1
kind: Service
metadata:
  labels:
    app: drkiq
  name: drkiq
  namespace: test
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: drkiq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
