apiVersion: v1
kind: ConfigMap
metadata:
  name: drkiq-config
  labels:
    app: drkiq
data:
  LISTEN_ON: "0.0.0.0:8010"
  USER_ID: "1000"
  GROUP_ID: "1000"
  WORKER_PROCESSES: "1"
  JOB_WORKER_URL: "redis://redis:6379/0"
  CACHE_URL: "redis://redis:6379/0"
  DATABASE_URL: "postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000" 
  SECRET_TOKEN: "Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw"
