apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "90"
    kubectl.kubernetes.io/last-applied-configuration: |
  labels:
    app: sidekiq
  name: sidekiq
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sidekiq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      creationTimestamp: null
      labels:
        app: sidekiq
    spec:
      containers:
      - env:
        envFrom:
        - configMapRef:
            name: drkiq-config              
        image: 665444087826.dkr.ecr.eu-west-1.amazonaws.com/sidekiq:latest
        imagePullPolicy: Always
        name: sidekiq
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
